Add parentId, Enums and delete stringify hell
novom/belenios-api pull request #16
Opened 2022-05-17 14:02 UTC by GeorgesMainville

**À quelle story correspond cette pull request?**
Aucune

**Qu'est-ce que cette pull request fait?**
- Remplace le "stringify hell" par des types graphql
- Ajoute un paramêtre `parentId` au `Election` se qui permet d'avoir une relation enfant parent avec une resource externe.
- Ajoute un enum pour les statuts de l'élection.
- Sauvgarde les valeurs du `computeVoters` dans l'élection.

**Qu'est-ce que cette pull request ne fait pas (en lien avec la story)?**

**Comment faire pour tester cette pull request?**
- Déployer et tester le endpoint directement

**Description du design (conception technique):**

**Capture(s) d'écran:**

2022-05-17 17:28 UTC, Samarkial approved these changes

2022-05-17 21:21 UTC, SeallySeal approved these changes

2022-05-18 15:28 UTC, ssideleau requested changes

2022-05-18 15:28 UTC, ssideleau commented on src/lib/belenios/voter/vote.js
> +    const encryptedBallot = execSync(`bash src/scripts/vote.sh ${privCred} ${stringifyBallot} ${electionDir}`).toString();
Ici on serait mieux d'utiliser `execFileSync`. `execSync` est généralement dangereux lorsqu'il y a des inputs du user.  

Ex:
```javascript
function vote(electionId, privCred, ballot) {
  // privCred = '; malicious_command'
  try {
    const electionDir = path.join(ELECTIONS_DIR, electionId);
    const stringifyBallot = JSON.stringify(ballot);
    const encryptedBallot = execSync(`bash src/scripts/vote.sh ${privCred} ${stringifyBallot} ${electionDir}`).toString();
   // execSync(`bash src/scripts/vote.sh ;malicious_command ${stringifyBallot} ${electionDir}`)`
```
La commande malicieuse pourrait par exemple être cat <code_location>/src/settings/production.json ce qui retournerait le contenu du fichier et par conséquant la clé JWT s'il y en a une dans ce projet.

Il y a un petit travail à faire pour savoir ou est le code location mais on peux aussi faire des ls et autres pour le trouver.

2022-05-18 15:28 UTC, ssideleau commented on src/lib/belenios/admin/makeElection.js
>      execSync(`bash src/scripts/makeElection.sh ${electionId} ${templateFilePath} ${GROUP_FILE_PATH} ${electionDir}`);
Voir mon autre commentaire sur les `execSync` et `exec` ca serait pertinent de chercher dans le code base au complet pour voir s'il y en a d'autre.

2022-05-25 13:58 UTC, merged