Lambda deploy script
novom/belenios-api pull request #3
Opened 2021-08-09 20:18 UTC by GeorgesMainville

Qu'est-ce que cette pull request fait?
Ajout du script pour déployer la lambda de création du ballot sur AWS.

Le fichier `samconfig.toml` n'est pas inclus puisqu'il s'agit d'un repo public et que le fichier contient des informations propres à chaque environnement de déploiement.

2021-08-10 13:29 UTC, Samarkial approved these changes

2021-08-10 14:24 UTC, Keny9 approved these changes

2021-08-11 19:41 UTC, ssideleau requested changes

2021-08-11 19:41 UTC, ssideleau commented on belenios-ballot-lambda/package.json
> +    "babel-eslint": "^10.1.0",
Ca devrais pas plutôt être dans les devDependencies?

2021-08-16 19:19 UTC, merged