Belenios lambda
novom/belenios-api pull request #5
Opened 2021-10-25 19:57 UTC by GeorgesMainville

**À quelle story correspond cette pull request?**
[Belenios Api lambda](https://app.shortcut.com/novom/story/4289/belenios-api-lambda)

Reprend l'API belenios fait avec socket io pour en faire une avec lambda.

**Qu'est-ce que cette pull request fait?**
- Création d'un serveur GraphQL:
   - Queries:
      - getAllElectionVotes
      - getElection
      - getElections
   - Mutation:
      - openElection
      - closeElection
      - computeVoters
      - joinElection
      - vote
- Config de déploiement sur AWS: 
   - Lambda
   - DynamoDB
- Refactor du wraper js autour de belenios-tool pour enlever les callback et utiliser des fonction sync.

**Qu'est-ce que cette pull request ne fait pas (en lien avec la story)?**
- Ajout de l'auth 
- Ajout de l'acl
- Gestion de la data consistency.

**Comment faire pour tester cette pull request?**
- `yarn deploy:development`
- Tester directement le endpoint générer.

**Description du design (conception technique):**

**Capture(s) d'écran:**

2021-11-01 15:38 UTC, ssideleau approved these changes

2021-11-01 15:45 UTC, Samarkial requested changes

2021-11-01 15:45 UTC, Samarkial commented on .babelrc
> +    "@babel/plugin-proposal-optional-chaining",
Normalement t'as pas besoin du plugin vu qu'il est inclus dans node 14 ! ( si la machine sur laquel tu fais rouler ça roule bien sur node 14) https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2021-11-01 15:45 UTC, Samarkial commented on src/lib/belenios/voter/joinElection.js
> +    const user = users.filter((u) => u && u.startsWith(`${userId},`));
tu peux faire un find, ça va arrêter dès que sa trouve le user so sa fait que t'aura pas toujours ton worst case que la liste est parcourue au complet

2021-11-01 15:45 UTC, Samarkial commented on src/lib/dynamoDB/dynamoDBDocumentClient.js
> +import { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';
Copy pasta ? Y'a beaucoup de commentaires inutiles dans ce fichier

2021-11-03 14:55 UTC, GeorgesMainville commented on src/lib/dynamoDB/dynamoDBDocumentClient.js
> +import { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';
yeah directement de la doc je vais le clean un peu

2021-11-03 14:55 UTC, GeorgesMainville commented on .babelrc
> +    "@babel/plugin-proposal-optional-chaining",
Bonne idée de l'enlever mon nvm rc est a 14.16 en plus.

2021-11-08 19:12 UTC, Samarkial approved these changes

2021-11-08 19:12 UTC, Samarkial commented on package.json
> +    "babel-eslint": "^10.1.0",
https://www.npmjs.com/package/babel-eslint c'est deprecated, c'est maintenant @babel/eslint-parser

2021-11-08 20:06 UTC, merged