Data consistency
novom/belenios-api pull request #6
Opened 2021-10-26 22:03 UTC by GeorgesMainville

**À quelle story correspond cette pull request?**
[Belenios Api lambda](https://app.shortcut.com/novom/story/4289/belenios-api-lambda)

Reprend l'API belenios fait avec socket io pour en faire une avec lambda.

**Qu'est-ce que cette pull request fait?**
- Utilise des transaction pour s'assurer que le vote envoyer sera réèlement pris en compte.
- Fait le décompte du nombre de versions de vote anvant de fermer le vote pour s'assurer que tous les votes sont présent avant de le fermer.
- Add personal stage

**Qu'est-ce que cette pull request ne fait pas (en lien avec la story)?**
- Ajout de l'auth 
- Ajout de l'acl

**Comment faire pour tester cette pull request?**
- `yarn deploy {youPersonnalStage}`
- Tester directement le endpoint générer.

**Description du design (conception technique):**

**Capture(s) d'écran:**

2021-11-08 21:13 UTC, Samarkial approved these changes

2021-11-09 14:16 UTC, Vymex requested changes

2021-11-09 14:16 UTC, Vymex commented on src/graphql/entities/election/resolver.js
> +      return election.electionResult || tryCloseElection(election, 3);
un retour de setTimeout à graphql? Je pense pas que le client va pouvoir faire grand chose avec cet info là. D'ailleurs, un setTimeout sur une instance lambda ne servira pas a grand chose puisque le processus node va être arrêté peu de temps après la fin de la requête.

2021-11-09 19:51 UTC, Vymex requested changes

2021-11-09 19:51 UTC, Vymex commented on src/graphql/entities/election/resolver.js
> +        return tryCloseElection(retries - 1);
```suggestion
        return tryCloseElection(election, retries - 1);
```

2021-11-09 19:51 UTC, Vymex commented on src/graphql/entities/election/resolver.js
> +
j'ajouterais un sleep d'une couple de ms avant de réessayer

2021-11-10 16:22 UTC, Vymex approved these changes

2021-11-11 15:10 UTC, ssideleau approved these changes

2021-11-15 15:29 UTC, merged