Add sample setting file
novom/belenios-api pull request #8
Opened 2021-11-23 23:04 UTC by GeorgesMainville

2021-11-24 18:58 UTC, ssideleau approved these changes

2021-11-24 18:58 UTC, ssideleau commented on package.json
> +    "deploy:undeploy": "bash scripts/deploy.sh ca-central-1 development",
Pas mal certain que c'est plus ca:
```suggestion
    "deploy:undeploy": "bash scripts/undeploy.sh ca-central-1 development",
```

2021-11-24 18:58 UTC, ssideleau commented on src/lib/belenios/admin/countMaxVotesAndVoters.js
> +  );
Optimisation: Le map n'est pas nécéssaire tu passes 2 fois dans tes voters alors que tu pourrais simplement le faire une fois dans le reduce
```suggestion
  const maxVotes = voters.reduce(
    (weightAcc, { weight }) => weightAcc + weight,
    0,
  );
```

2021-11-24 18:59 UTC, ssideleau requested changes
J'ai approve par accident s.v.p. faire les modifications

2021-11-25 21:24 UTC, GeorgesMainville commented on src/lib/belenios/admin/countMaxVotesAndVoters.js
> +  );
![image](https://user-images.githubusercontent.com/26386976/143501043-efaa60d5-da28-4b5b-b7e6-3e83f85be608.png)

2021-11-26 15:07 UTC, ssideleau approved these changes

2021-11-29 15:03 UTC, Samarkial approved these changes

2021-11-29 18:56 UTC, merged